#Makefile

#Compiler
CC = gcc

#Source file
MAIN = ojt_1.c

#Target executable
TARGET = ojt_1

#Default target
all: $(TARGET)

$(TARGET): $(MAIN)
		$(CC) -o $(TARGET) $(MAIN)		

#Make clean
clean:
		rm -f $(TARGET)

